### ISSUE TITLE
"Flatten" (?) dining menu result dict a bit

### ISSUE THREAD

**Issue by simon-andrews** [simon-andrews/umass-toolkit#19]
So instead of
```json
{
  "lunch":
  {
    "soups":
    {
      "Chicken Noodle Soup":
      {
        "prop1": "...",
        "prop2": "..."
      }
    }
  }
}
```
it's a list more like
```json
[
  "Chicken Noodle Soup":
  {
    "meal": "lunch",
    "category": "soup",
    "prop1": "...",
    "prop2": "..."
  }
]
```

**Comment by mattrossman** [comment]
The suggested reponse looks more like a dict than a list, do you want to toss the dish name in there too so it's returning a list of dicts instead of a dict of dicts?

e.g.
```
[
  {
    "dish-name": "Chicken Noodle Soup",
    "meal": "lunch",
    "category": "soup",
    "prop1": "...",
    "prop2": "..."
  }
]
```
That might make it a tad more intuitive to iterate over since the user would probably expect a menu to be structured as a list of self-contained meals objects.

**Comment by simon-andrews** [comment]
Yes, that makes more sense.
